services:
  - type: web
    name: cellsinvitro-api
    runtime: node
    buildCommand: npm install && npm run build --workspace=server
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "22"
